[project]
name = "ml-statistics-itmo"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "numpy==2.3.5",
    "pandas==2.3.3",
    "scipy>=1.15",
    "scikit-learn==1.7.2",
    "matplotlib==3.10.7",
    "seaborn==0.13.2",
    "plotly==5.24.1",
    "networkx==3.6.1",
    "graphviz==0.20.1",
    "h5py==3.16.0",
    "torch==2.6.0",
    "torchvision==0.21.0",
    "torchaudio==2.6.0",
    "keras>=3.12,<4.0",
    "openTSNE>=1.0",
    "kagglehub>=0.3",
    "gdown>=5.0",
    "joblib>=1.4",
    "tqdm==4.66.5",
    "jupyter>=1.0",
    "ipykernel==7.0.1",
    "pillow>=10.0",
    "lightgbm>=4.0",
    "xgboost>=2.0",
    "catboost>=1.2",
    "category-encoders>=2.6",
    "mlxtend>=0.23",
    "opencv-python>=4.8",
    "array2gif>=1.0",
    "nltk>=3.8",
    "sentence-transformers>=3.0",
    "transformers>=4.40",
    "datasets>=2.14",
]
